name: Deformation
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.1.*
  - python=3.7.*
  - sqlite=3.36.*
  - pip:
    - matplotlib==3.4.*
    - meshio==4.4.*
    - mpmath==1.2.*
    - msgpack==1.0.*
    - networkx==2.5.*
    - numpy==1.21.*
    - pillow==8.2.*
    - pyvista==0.31.*
    - requests==2.25.*
    - rtree==0.9.*
    - scipy==1.7.*
    - scooby==0.5.*
    - shapely==1.7.*
    - svg-path==4.*
    - sympy==1.*
    - tqdm==4.61.*
    - transforms3d==0.3.*
    - trimesh==3.9.*
    - vedo==2021.0.*
